# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
executors:
  j11:
    docker:
      - image: 'cimg/openjdk:11.0'

orbs:
  # Declare a dependency on the welcome-orb
  maven: circleci/maven@0.0.12 
  # Orchestrate or schedule a set of jobs
workflows:
  maven_test: 
  # Name the workflow "welcome"
     jobs:
      - maven/test:
          matrix:
            parameters:
              executor:
                - j11

